name: Black Ink Photography
favicon: null
layout_spectrum: 0.49759
typography_spectrum: 0.50211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf4f1'
    - '#0b0513'
    - '#647070'
    - '#9250e8'
    - '#8ba49e'
  brandStrength: 0.125
  lightness: 0.3468316993676126
  saturation: 0.5
  rhythmicContrast: 0.7274782527238131
purpose: []
