typography_spectrum: 0.50211
color:
  brandColors:
    - '#ebf4f1'
    - '#0b0513'
    - '#647070'
    - '#9250e8'
    - '#8ba49e'
  brandStrength: 0.125
  lightness: 0.3468316993676126
  saturation: 0.5
  rhythmicContrast: 0.7274782527238131
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99579
analytics:
  google: null
  facebook: null
  twitter: null
name: Black Ink Photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Store
    url: 'https://www.galloree.com/FB/Black-Ink-Photography-Merch-6183.htm'
    type: external
favicon: null
purpose: []
